### PR TITLE
Fixed skipping of existing pages and added a force download option

### PR DESCRIPTION
**Pull request by thetuxkeeper**

### CODE REVIEW

**Comment by jphager2** [comment]
hey, cool. i didn't notice this bug. I think your way of solving it is good. very clear what's going on. Just one little thing that stuck out to me is the use of `and` instead of `&&` for logic. I pretty much always use `&&` in ruby unless I have one concise line that needs flow control like: `eat and sleep and wake_up`. I'll make some comments on the file changes.

**Comment by thetuxkeeper** [comment]
Here's the rebased and improved version :)

**Comment by thetuxkeeper** [comment]
I found some more "&& <-> and" parts

**Comment by jphager2** [comment]
Hey, I noticed some things and I am going to make some small changes, but I will merge this first and work from there. Thanks for noticing the bugs and adding the force download feature.

**Comment by thetuxkeeper** [comment]
Thanks for reviewing and merging :)

**Pull request merged**
